---
title: "Probability Intro"
author: "Jason Freels"
date: "12/20/2019"
output: html_document
---

# Overview

## Definitions

Probability: the branch of mathematics dealing with calculating the likelihood of an event's occurrence, which is expressed as a number between 0 and 1.

Statistics: the science of collecting and analyzing numerical data for the purpose of making inferences and/or predictions about a population.

## Probability & Statistics

You may already know that probability and statistics are related.  This lecture will help you understand this relationship.  To do this we'll use the following terms:

- Experiment
- Outcome
- Sample space
- Event
- Borel Sigma-Algebra
- Random Variable
- Statistic

### Experiment

An experiment is a scientific procedure undertaken to make a discovery, test a hypothesis, or demonstrate a known fact. This is accomplished by analyzing the data generated throughout the experiment.

When you hear the word experiment you may be thinking of scientists in lab coats or remembering back to you experiences in a Chemistry class. While these are accurate representations of an experiment, I'd like for you to think more broadly - think of an experiment simply as a process that generates data that will be used to help make some decision. 

As a data analyst, it's likely that your weren't involved in setting up an experiment.  Instead, you were asked to analyze some data that had already been collected

From this definition we see that we are surrounded by experiments

- The time required for a computer to boot up each morning
- The result of a coin flip
- The result fo rolling a die

Understanding the type of data generated by an experiment and the manner in which the data are collected are crucial to selecting a valid approach  best to model the data   

```{block, echo=F}
IN SOME CASES YOU ARE PART OF AN EXPERIMENT

Need to discuss the work to set up an experiment make sure data supports the decision to be made or hypothesis to be tested

As analyst 

- may be asked to design experiment to collect data used to make decision
- May be asked to use already collected data to determine which decision to make (more common situation)

- Often data is collected without fully understanding the experiments that will be used or the the experiments change over time and the data collected does not provide sufficient infor to answer new questions 
```

For the rest of this lecture we'll use a simple experiment in which we roll a 6-sided die one or more times 

### Outcomes

An outcome is any result that could <u>possibly</u> be observed from an experiment.  If our experiment involved a single roll of a 6-sided die, it is trivial to say that the possible outcomes are $\{1\}$, $\{2\}$, $\{3\}$, $\{4\}$, $\{5\}$, or $\{6\}$. Similarly we understand that an impossible outcome would be any number that is not an integer and any integer that is either less than zero or greater that 7.

Note that each outcome is enclosed within curly brackets 

Suppose, an experiment involves rolling a 6-sided die two times, what would some possible outcomes be?  Many times when I ask students this question the response is "Any number between 2 and 12" - but this is incorrect.  This response assumes that I want you to take the result of the two rolls and add them together. While I may eventually ask you to do this, this is not the same as the possible outcomes 
may as  some possible outcomes would be $\{1,5\}$, $\{3,1\}$, or $\{6,6\}$. An outcome that would not be possible would be $\{7,2\}$.

### Sample space

The sample space refers to the collection of all possible outcomes that could result from an experiment In the literature the sample space is often denoted by the Greek capital letter omega $\Omega$ or a capital script "S" $\mathcal{S}$

### Events

An event is a set of outcomes from an experiment (a subset of the sample space) to which a probability can be assigned. A single outcome may be an element of many different events, and different events in an experiment are usually not equally likely, since they may include very different groups of outcomes.

### Random Variable

Informally, a random variable defined as a variable whose value is random (duh).


### Borel Sigma-Algebra

Represents the mapping of the outcomes to the events

### Statistic
