---
title: "Basic Statistics"
author: "Jason Freels"
date: "12/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

Data analyses involving basic statistical methods can be broken into two main areas - descriptive statistics and inferential statistics.  Descriptive statistics uses tools like mean and standard deviation on a sample to summarize data.
Inferential statistics, on the other hand, looks at data that can randomly vary, and then draw conclusions from it.
In this presentation you'll learn how to use Python to implement various methods from both of these areas.  For this class it will not be assumed that you have the Python language installed on your machine.  Rather, you will use a cloud based interface to work with the code. In later DASC courses, you'll learn how to install Python, and any required libraries, on your local machine.

## Descriptive Statistics

Descriptive statistics are measures used to represent either an entire population or a sample of a population. Descriptive statistics help analysts communicate the features of a specific data set by giving short summaries about the measures of central tendency and measures of dispersion (variability).  

Measures of central tendency describe the center position of a distribution for a data set. The most commonly used measures of central tendency include the mean, median, and mode

Measures of variability, or the measures of spread, aid in analyzing how spread-out the distribution is for a set of data. For example, while a measure of central tendency may describe the average value for a data set, it does not describe how the data is distributed within the set. So, while the average of the data may be 65 out of 100, there can still be data points at both 1 and 100. Measures of variability help communicate this by describing the shape and spread of the data set. the most commonly used measures of variability include the standard deviation, variance, the minimum and maximum variables, and the kurtosis and skewness, Range, quartiles, absolute deviation.


People use descriptive statistics to repurpose hard-to-understand quantitative insights across a large data set into bite-sized descriptions. A student's grade point average (GPA), for example, provides a good understanding of descriptive statistics. The idea of a GPA is that it takes data points from a wide range of exams, classes, and grades, and averages them together to provide a general understanding of a student's overall academic abilities. A student's personal GPA reflects his mean academic performance.

The mean, or the average, is calculated by adding all the figures within the data set and then dividing by the number of figures within the set. For example, the sum of the following data set is 20: (2, 3, 4, 5, 6). The mean is 4 (20/5). The mode of a data set is the value appearing most often, and the median is the figure situated in the middle of the data set. It is the figure separating the higher figures from the lower figures within a data set. However, there are less-common types of descriptive statistics that are still very important.




All descriptive statistics are either measures of central tendency or measures of variability, also known as measures of dispersion. Measures of central tendency focus on the average or middle values of data sets; whereas, measures of variability focus on the dispersion of data. These two measures use graphs, tables, and general discussions to help people understand the meaning of the analyzed data.





Descriptive Statistics in Python
Python Descriptive Statistics process describes the basic features of data in a study. It delivers summaries on the sample and the measures and does not use the data to learn about the population it represents.
Under descriptive statistics, fall two sets of properties- central tendency and dispersion. Python Central tendency characterizes one central value for the entire distribution. Measures under this include mean, median, and mode. Python Dispersion is the term for a practice that characterizes how apart the members of the distribution are from the center and from each other. Variance/Standard Deviation is one such measure of variability.

4. Python Descriptive Statistics – Central Tendency in Python
We have seen what central tendency or central location is. Now let’s take a look at all the functions Python caters to us to calculate the central tendency for a distribution. For this, let’s import the Python statistics module.
a. mean()
This function returns the arithmetic average of the data it operates on. If called on an empty container of data, it raises a StatisticsError.

>>> nums=[1,2,3,5,7,9]
>>> st.mean(nums)
4.5

>>> st.mean([-2,-4,7]) #Negative numbers
0.3333333333333333

>>> from fractions import Fraction as fr
>>> st.mean((fr(3,4),fr(5,7),fr(2,1))) #Fractions
Fraction(97, 84)

>>> st.mean({1:"one",2:"two",3:"three"}) #Keys from a dictionary
2
Do you know the difference between Python Modules vs Packages

b. mode()
This function returns the most common value in a set of data. This gives us a great idea of where the center lies.

>>> nums=[1,2,3,5,7,9,7,2,7,6]
>>> st.mode(nums)
7

>>> st.mode(['A','B','b','B','A','B'])
‘B’

c. median()
For data of odd length, this returns the middle item; for that of even length, it returns the average of the two middle items.

>>> st.median(nums) #(5+6)/2
5.5

d. harmonic_mean()
This function returns the harmonic mean of the data. For three values a, b, and c, the harmonic mean is-
3/(1/a + 1/b +1/c)
It is a measure of the center; one such example would be speed.

>>> st.harmonic_mean([2,4,9.7])
3.516616314199396
For the same set of data, the arithmetic mean would give us a value of 5.233333333333333.

e. median_low()
When the data is of an even length, this provides us the low median of the data. Otherwise, it returns the middle value.

>>> st.median_low([1,2,4])
2

>>> st.median_low([1,2,3,4])
2

f. median_high()
Like median_low, this returns the high median when the data is of an even length. Otherwise, it returns the middle value.

>>> st.median_high([1,2,4])
2

>>> st.median_high([1,2,3,4])
3
Let’s Learn CGI Programming in Python with Functions and Modules

g. median_grouped()
This function uses interpolation to return the median of grouped continuous data. This is the 50th percentile.

>>> st.median([1,3,3,5,7])
3

>>> st.median_grouped([1,3,3,5,7],interval=1)
3.25

>>> st.median_grouped([1,3,3,5,7],interval=2)
3.5

5. Python Descriptive Statistics – Dispersion in Python
Dispersion/spread gives us an idea of how the data strays from the typical value.



In this presentation we'll learn how to use Python to  Descriptive Statistics. In this Python Statistics tutorial, we will discuss what is Data Analysis, Central Tendency in Python: mean, median, and mode. Moreover, we will discuss Python Dispersion and Python Pandas Descriptive Statistics. Along with this, we will cover the variance in Python and how to calculate the variability for a set of values.

